// ── Shared seed store definitions ─────────────────────────────────────────────
// These are the canonical store entries for Snatchd NYC.
// Imported by the stores list page (auto-seed on load) and settings page.

export const SEED_STORES = [
    {
        name: "Louis Vuitton",
        description: "Iconic French luxury fashion house known for its monogram canvas goods, ready-to-wear, and accessories.",
        category: "Luxury Fashion",
        categories: ["Luxury Fashion", "Accessories", "Clothing"],
        deliveryTime: "35 Mins",
        address: "116 Greene St, New York, NY 10012",
        latitude: 40.7243,
        longitude: -74.0004,
        deliveryRadius: 8,
        externalId: "",
        logo: "",
        image: "",
    },
    {
        name: "Nike",
        description: "World's leading athletic footwear and apparel brand.",
        category: "Sportswear",
        categories: ["Sportswear", "Shoes", "Clothing"],
        deliveryTime: "45 Mins",
        address: "529 Broadway, New York, NY 10012",
        latitude: 40.7228,
        longitude: -73.9981,
        deliveryRadius: 8,
        externalId: "",
        logo: "",
        image: "",
    },
    {
        name: "Aime Leon Dore",
        description: "New York-based label blending sportswear, tailoring, and vintage references.",
        category: "Streetwear",
        categories: ["Streetwear", "Clothing", "Accessories"],
        deliveryTime: "50 Mins",
        address: "232 Mulberry St, New York, NY 10012",
        latitude: 40.7224,
        longitude: -73.9963,
        deliveryRadius: 8,
        externalId: "",
        logo: "",
        image: "",
    },
    {
        name: "Kith",
        description: "Lifestyle brand and retailer blending fashion, food, and culture.",
        category: "Streetwear",
        categories: ["Streetwear", "Clothing", "Shoes"],
        deliveryTime: "40 Mins",
        address: "337 Lafayette St, New York, NY 10012",
        latitude: 40.7256,
        longitude: -73.9962,
        deliveryRadius: 8,
        externalId: "",
        logo: "",
        image: "",
    },
    {
        name: "Miu Miu",
        description: "Prada's sister label — playfully intellectual, feminine, and eccentric.",
        category: "Luxury Fashion",
        categories: ["Luxury Fashion", "Clothing", "Accessories"],
        deliveryTime: "35 Mins",
        address: "100 Prince St, New York, NY 10012",
        latitude: 40.7254,
        longitude: -74.0002,
        deliveryRadius: 8,
        externalId: "",
        logo: "",
        image: "",
    },
    {
        name: "Jacquemus",
        description: "Provençal French brand known for its minimalist, sun-soaked aesthetic.",
        category: "Luxury Fashion",
        categories: ["Luxury Fashion", "Clothing", "Accessories"],
        deliveryTime: "45 Mins",
        address: "98 Prince St, New York, NY 10012",
        latitude: 40.7252,
        longitude: -73.9999,
        deliveryRadius: 8,
        externalId: "",
        logo: "",
        image: "",
    },
    {
        name: "Bergdorf Goodman",
        description: "New York's premier luxury department store on Fifth Avenue.",
        category: "Luxury Department Store",
        categories: ["Luxury Fashion", "Beauty & Skincare", "Fine Jewelry", "Clothing"],
        deliveryTime: "60 Mins",
        address: "754 5th Ave, New York, NY 10019",
        latitude: 40.7641,
        longitude: -73.9727,
        deliveryRadius: 10,
        externalId: "",
        logo: "",
        image: "",
    },
    {
        name: "Alo",
        description: "Mindful movement brand for yoga, fitness, and beyond.",
        category: "Activewear",
        categories: ["Activewear", "Clothing", "Accessories"],
        deliveryTime: "30 Mins",
        address: "136 Prince St, New York, NY 10012",
        latitude: 40.7256,
        longitude: -74.0008,
        deliveryRadius: 8,
        externalId: "",
        logo: "",
        image: "",
    },
    {
        name: "Cos",
        description: "Modern, functional, and considered design for women and men.",
        category: "Modern Essentials",
        categories: ["Clothing", "Accessories"],
        deliveryTime: "40 Mins",
        address: "129 Spring St, New York, NY 10012",
        latitude: 40.7248,
        longitude: -74.0009,
        deliveryRadius: 8,
        externalId: "",
        logo: "",
        image: "",
    },
    {
        name: "Aesop",
        description: "Australian skincare brand formulated from plant-based and laboratory-made ingredients.",
        category: "Luxury Boutique",
        categories: ["Beauty & Skincare", "Hygiene"],
        deliveryTime: "60 Mins",
        address: "87 Greene St, New York, NY 10012",
        latitude: 40.7238,
        longitude: -74.0003,
        deliveryRadius: 8,
        externalId: "",
        logo: "",
        image: "",
    },
    {
        name: "Chanel",
        description: "Timeless French luxury house — fashion, fragrance, beauty, and fine jewelry.",
        category: "Beauty & Fragrance",
        categories: ["Beauty & Skincare", "Fine Jewelry", "Clothing", "Fragrance"],
        deliveryTime: "55 Mins",
        address: "15 E 57th St, New York, NY 10022",
        latitude: 40.7625,
        longitude: -73.9726,
        deliveryRadius: 10,
        externalId: "",
        logo: "",
        image: "",
    },
    {
        name: "Skims",
        description: "Solutions-oriented brand creating the next generation of basics by Kim Kardashian.",
        category: "Modern Basics",
        categories: ["Clothing", "Accessories"],
        deliveryTime: "40 Mins",
        address: "494 Broadway, New York, NY 10012",
        latitude: 40.7221,
        longitude: -73.9986,
        deliveryRadius: 8,
        externalId: "",
        logo: "",
        image: "",
    },
];

export const SEED_MULTI_LOCATION_STORES = [
    // ── Apple ────────────────────────────────────────────────────────────────
    {
        name: "Apple SoHo",
        description: "Apple retail store in SoHo — iPhone, Mac, iPad, and accessories.",
        category: "Electronics",
        categories: ["Electronics", "Accessories"],
        deliveryTime: "35 Mins",
        address: "103 Prince St, New York, NY 10012",
        latitude: 40.7254,
        longitude: -73.9971,
        deliveryRadius: 5,
        externalId: "",
        logo: "",
        image: "",
    },
    {
        name: "Apple Fifth Avenue",
        description: "Apple's iconic 24-hour glass cube store on Fifth Avenue.",
        category: "Electronics",
        categories: ["Electronics", "Accessories"],
        deliveryTime: "40 Mins",
        address: "767 5th Ave, New York, NY 10153",
        latitude: 40.7636,
        longitude: -73.9727,
        deliveryRadius: 5,
        externalId: "",
        logo: "",
        image: "",
    },
    {
        name: "Apple Upper West Side",
        description: "Apple retail store on the Upper West Side.",
        category: "Electronics",
        categories: ["Electronics", "Accessories"],
        deliveryTime: "40 Mins",
        address: "1981 Broadway, New York, NY 10023",
        latitude: 40.7676,
        longitude: -73.9820,
        deliveryRadius: 5,
        externalId: "",
        logo: "",
        image: "",
    },
    {
        name: "Apple Grand Central",
        description: "Apple retail store inside Grand Central Terminal.",
        category: "Electronics",
        categories: ["Electronics", "Accessories"],
        deliveryTime: "40 Mins",
        address: "45 Grand Central Terminal, New York, NY 10017",
        latitude: 40.7527,
        longitude: -73.9773,
        deliveryRadius: 5,
        externalId: "",
        logo: "",
        image: "",
    },
    // ── Zara ─────────────────────────────────────────────────────────────────
    {
        name: "Zara SoHo",
        description: "Zara's flagship SoHo store — women's, men's, and kids' fashion.",
        category: "Fast Fashion",
        categories: ["Clothing", "Accessories"],
        deliveryTime: "35 Mins",
        address: "580 Broadway, New York, NY 10012",
        latitude: 40.7239,
        longitude: -73.9982,
        deliveryRadius: 5,
        externalId: "",
        logo: "",
        image: "",
    },
    {
        name: "Zara Fifth Avenue",
        description: "Zara on Fifth Avenue — multi-floor fashion destination.",
        category: "Fast Fashion",
        categories: ["Clothing", "Accessories"],
        deliveryTime: "40 Mins",
        address: "666 5th Ave, New York, NY 10103",
        latitude: 40.7596,
        longitude: -73.9789,
        deliveryRadius: 5,
        externalId: "",
        logo: "",
        image: "",
    },
    {
        name: "Zara Columbus Circle",
        description: "Zara at the Time Warner Center, Columbus Circle.",
        category: "Fast Fashion",
        categories: ["Clothing", "Accessories"],
        deliveryTime: "40 Mins",
        address: "10 Columbus Circle, New York, NY 10019",
        latitude: 40.7683,
        longitude: -73.9836,
        deliveryRadius: 5,
        externalId: "",
        logo: "",
        image: "",
    },
    {
        name: "Zara Midtown East",
        description: "Zara on Lexington Avenue in Midtown East.",
        category: "Fast Fashion",
        categories: ["Clothing", "Accessories"],
        deliveryTime: "40 Mins",
        address: "750 Lexington Ave, New York, NY 10022",
        latitude: 40.7628,
        longitude: -73.9674,
        deliveryRadius: 5,
        externalId: "",
        logo: "",
        image: "",
    },
    // ── Aesop ─────────────────────────────────────────────────────────────────
    {
        name: "Aesop West Village",
        description: "Aesop skincare boutique in the West Village.",
        category: "Luxury Boutique",
        categories: ["Beauty & Skincare", "Hygiene"],
        deliveryTime: "45 Mins",
        address: "232 W 10th St, New York, NY 10014",
        latitude: 40.7327,
        longitude: -74.0058,
        deliveryRadius: 5,
        externalId: "",
        logo: "",
        image: "",
    },
    {
        name: "Aesop Upper East Side",
        description: "Aesop skincare boutique on Madison Avenue, UES.",
        category: "Luxury Boutique",
        categories: ["Beauty & Skincare", "Hygiene"],
        deliveryTime: "45 Mins",
        address: "870 Madison Ave, New York, NY 10021",
        latitude: 40.7710,
        longitude: -73.9643,
        deliveryRadius: 5,
        externalId: "",
        logo: "",
        image: "",
    },
    // ── Alo ───────────────────────────────────────────────────────────────────
    {
        name: "Alo Upper East Side",
        description: "Alo Yoga flagship on the Upper East Side.",
        category: "Activewear",
        categories: ["Activewear", "Clothing", "Accessories"],
        deliveryTime: "40 Mins",
        address: "981 Madison Ave, New York, NY 10075",
        latitude: 40.7731,
        longitude: -73.9635,
        deliveryRadius: 5,
        externalId: "",
        logo: "",
        image: "",
    },
    {
        name: "Alo Flatiron",
        description: "Alo Yoga store in the Flatiron District.",
        category: "Activewear",
        categories: ["Activewear", "Clothing", "Accessories"],
        deliveryTime: "40 Mins",
        address: "156 5th Ave, New York, NY 10010",
        latitude: 40.7411,
        longitude: -73.9891,
        deliveryRadius: 5,
        externalId: "",
        logo: "",
        image: "",
    },
];

export type SeedStore = typeof SEED_STORES[number];
